version: "3.9"
services:
  ecommerce-cms-db:
    image: postgres
    restart: always
    container_name: ecommerce-cms
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "ecommerce-cms"
      POSTGRES_PASSWORD: "ecommerce-cms"
      PGDATA: "/data/postgres"
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
